Repository TriauNicolas/SQLizer, pull requests merged in 2023-10, with the labels that each got.

#10 Refacto Canvas
  src/components/Canvas/CanvasElement.tsx
  src/components/Canvas/CanvasInstance.tsx
  src/components/InfosTable/InfosTable.module.css
  src/components/InfosTable/InfosTable.tsx
  src/hooks/useAddTableNode.ts
  src/hooks/useDownloadSql.ts
  src/hooks/useEdges.ts
  src/hooks/useNodes.ts
  src/hooks/useSocketsManager.ts
  src/styles/auth.css
  src/styles/page.module.css
  src/utils/auth.utils.ts
Labels: bug, enhancement

#11 Ft/Next-Auth
  .env.proto
  app/SessionProvider.tsx
  app/api/auth/[...nextauth]/route.ts
  app/layout.tsx
  app/login/page.tsx
  app/page.tsx
  app/register/page.tsx
  middleware.ts
  next.config.js
  package-lock.json
  package.json
  src/api/axios.ts
  src/api/fetch.ts
  src/hooks/useApi.ts
  src/utils/auth.utils.ts
Labels: enhancement

#14 Sockets
  src/components/Canvas/CanvasElement.tsx
  src/components/Canvas/CanvasInstance.tsx
  src/components/FieldModal/FieldModal.tsx
  src/components/FieldNode/FieldNode.tsx
  src/components/InfoField/InfoField.tsx
  src/components/InfosTable/InfosTable.tsx
  src/components/TableNode/TableNode.tsx
  src/hooks/useAddTableNode.ts
  src/hooks/useCRUDEdge.ts
  src/hooks/useCRUDFieldNode.ts
  src/hooks/useCRUDTableNode.ts
  src/hooks/useDataToJson.ts
  src/hooks/useDownloadSql.ts
  src/hooks/useEdges.ts
  src/hooks/useNodes.ts
  src/hooks/useSocketsManager.ts
  src/sockets/socketConnection.ts
  src/sockets/socketEmitter.ts
  src/types/infosTable.ts
  src/types/socketEvent.ts
  src/types/tables.ts
Labels: bug, enhancement

#16 Minors fixes in canvas
  src/components/FieldModal/FieldModal.module.css
  src/components/FieldNode/FieldNode.module.css
  src/components/TableNode/TableNode.tsx
  src/hooks/useCRUDTableNode.ts
  src/styles/globals.css
  src/styles/page.module.css
Labels: bug

#18 Change folder organization
  app/page.tsx
  middleware.ts
  src/components/CanvasComponents/AddFieldNode/AddFieldNode.module.css
  src/components/CanvasComponents/AddFieldNode/AddFieldNode.tsx
  src/components/CanvasComponents/Canvas/CanvasElement.tsx
  src/components/CanvasComponents/Canvas/CanvasInstance.module.css
  src/components/CanvasComponents/Canvas/CanvasInstance.tsx
  src/components/CanvasComponents/FieldModal/FieldModal.module.css
  src/components/CanvasComponents/FieldModal/FieldModal.tsx
  src/components/CanvasComponents/FieldNode/FieldNode.module.css
  src/components/CanvasComponents/FieldNode/FieldNode.tsx
  src/components/CanvasComponents/InfoField/InfoField.module.css
  src/components/CanvasComponents/InfoField/InfoField.tsx
  src/components/CanvasComponents/InfosTable/InfosTable.module.css
  src/components/CanvasComponents/InfosTable/InfosTable.tsx
  src/components/CanvasComponents/TableNode/TableNode.module.css
  src/components/CanvasComponents/TableNode/TableNode.tsx
  src/hooks/CanvasCRUD/useCRUDEdge.ts
  src/hooks/CanvasCRUD/useCRUDFieldNode.ts
  src/hooks/CanvasCRUD/useCRUDTableNode.ts
  src/hooks/CanvasNodesEdges/useEdges.ts
  src/hooks/CanvasNodesEdges/useNodes.ts
  src/hooks/CanvasSQLCall/useApi.ts
  src/hooks/CanvasSQLCall/useDataToJson.ts
  src/hooks/CanvasSQLCall/useDownloadSql.ts
  src/sockets/socketEmitter.ts
Labels: enhancement, don't merge

#19 User connexion to Canvas
  app/canvas/[canvasId]/page.tsx
  middleware.ts
  src/components/CanvasComponents/Canvas/CanvasElement.tsx
  src/components/CanvasComponents/Canvas/CanvasInstance.tsx
  src/components/CanvasComponents/FieldModal/FieldModal.tsx
  src/hooks/CanvasCRUD/useCRUDTableNode.ts
  src/hooks/CanvasNodesEdges/useEdges.ts
  src/hooks/CanvasNodesEdges/useInitDatas.ts
  src/hooks/CanvasNodesEdges/useNodes.ts
  src/sockets/socketConnection.ts
  src/types/socketEvent.ts
Labels: bug, enhancement
